version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb
    ports:
      - "5400:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build: 
      context: ./User Service   # Specify the correct folder
    container_name: user-service
    restart: always
    depends_on:
      - postgres
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: usersdb
    ports:
      - "3000:3000"

volumes:
  pgdata:
