apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: onlineeventbookingzakariyaabbas
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: onlineeventbookingzakariyaabbas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: zakariyaabbas/user-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URL_USER
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CORS_ORIGIN
            - name: BOOKING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BOOKING_SERVICE_URL
            - name: EVENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EVENT_SERVICE_URL
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
